### ISSUE TITLE
Feature: User can search for pokemon

### ISSUE THREAD

**Issue by cindy-le91** [cindy-le91/pokedex#1]
## ⚙️ User can search for pokemon

> ##### User can search for pokemon

## 📐 Functionality

>When user inputs a pokemon into search box, the desired pokemon is loaded from the pokeAPI and displayed on the page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] write html and css for page layout in initial state with header and input box
- [x] add placeholder image
- [x] add buttons for search and team
- [x] make sure that click targets are either `<a>` or `<button>` elements.
- [x] add event listener to search button
- [x] write function that queries API for pokemon typed in search input box
- [x] create a data.js file
- [x]  display pokemon and stats on top half of screen
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
