### ISSUE TITLE
Feature: User can add pokemon to pokedex

### ISSUE THREAD

**Issue by cindy-le91** [cindy-le91/pokedex#2]
## ⚙️ User can add pokemon to pokedex

> ##### User can add pokemon to pokedex

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] change + button to a star
- [x] add event listener to star (favorite) button
- [x] write function that saves pokemon to team
- [x] in data.js, add a 'beforeunload' event listener to the window object that serializes the data model as JSON and stores the JSON in localStorage
- [x] at the bottom of data.js, include a conditional statement that: checks to see if there is a JSON data model stored in localStorage.  if there is, parse it and assign it to the initial data variable so that the user can continue adding entries to the pre-existing data model.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
