### ISSUE TITLE
Feature: User can view pokemon in pokedex

### ISSUE THREAD

**Issue by cindy-le91** [cindy-le91/pokedex#3]
## ⚙️ User can view pokemon in pokedex

> ##### User can view pokemon in pokedex

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Write for loop that loops through team array and displays the sprites of the saved pokemon on top screen
- [x] add event listener within the loop that display stats of clicked sprite on top screen and moves team to bottom screen
- [x] remove input and search/ team buttons and add in a back button that takes user to main page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
