### ISSUE TITLE
Feature: User can update image view of pokemon

### ISSUE THREAD

**Issue by cindy-le91** [cindy-le91/pokedex#4]
## ⚙️ User can update image view of pokemon

> ##### User can update image view of pokemon

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create icon in HTML that will toggle the image of the pokemon
- [x] add event listener that listens for click event; when icon is clicked image changes to rare version of pokemon
- [x] add logic that toggles between the two images when icon is clicked
- [x] add image view to local storage
- [x] add page view to local storage
- [x] add searched pokemon to local storage
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
