### ISSUE TITLE
Feature: User can delete pokemon from pokedex

### ISSUE THREAD

**Issue by cindy-le91** [cindy-le91/pokedex#5]
## ⚙️ User can delete pokemon from pokedex

> ##### User can delete pokemon from pokedex

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add delete buttons to all pokemon in team view
- [x] add event listener to delete buttons
- [x] when delete button is clicked, modal appears asking to confirm or cancel
- [x] if user clicks cancel, modal closes; if user clicks confirm, remove pokemon from team
- [x] close modal when pokemon is removed
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
